"""add blocklist_entries table

Revision ID: bdec41326899
Revises: f76701351fc2
Create Date: 2026-07-16 06:44:18.509000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdec41326899'
down_revision: Union[str, None] = 'f76701351fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist_entries',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='autonomatex_enterprise'
    )
    op.create_index(op.f('ix_autonomatex_enterprise_blocklist_entries_kind'), 'blocklist_entries', ['kind'], unique=False, schema='autonomatex_enterprise')
    op.create_index(op.f('ix_autonomatex_enterprise_blocklist_entries_value'), 'blocklist_entries', ['value'], unique=False, schema='autonomatex_enterprise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autonomatex_enterprise_blocklist_entries_value'), table_name='blocklist_entries', schema='autonomatex_enterprise')
    op.drop_index(op.f('ix_autonomatex_enterprise_blocklist_entries_kind'), table_name='blocklist_entries', schema='autonomatex_enterprise')
    op.drop_table('blocklist_entries', schema='autonomatex_enterprise')
    # ### end Alembic commands ###
