"""initial enterprise schema (tenants, users, roles, user_roles)

Revision ID: f76701351fc2
Revises: 
Create Date: 2026-07-13 16:33:41.945333

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76701351fc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name'),
    schema='autonomatex_enterprise'
    )
    op.create_index(op.f('ix_autonomatex_enterprise_roles_tenant_id'), 'roles', ['tenant_id'], unique=False, schema='autonomatex_enterprise')
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='autonomatex_enterprise'
    )
    op.create_index(op.f('ix_autonomatex_enterprise_tenants_slug'), 'tenants', ['slug'], unique=True, schema='autonomatex_enterprise')
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    schema='autonomatex_enterprise'
    )
    op.create_index(op.f('ix_autonomatex_enterprise_users_email'), 'users', ['email'], unique=False, schema='autonomatex_enterprise')
    op.create_index(op.f('ix_autonomatex_enterprise_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='autonomatex_enterprise')
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['autonomatex_enterprise.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['autonomatex_enterprise.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'role_id', name='uq_user_roles'),
    schema='autonomatex_enterprise'
    )
    op.create_index(op.f('ix_autonomatex_enterprise_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False, schema='autonomatex_enterprise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autonomatex_enterprise_user_roles_tenant_id'), table_name='user_roles', schema='autonomatex_enterprise')
    op.drop_table('user_roles', schema='autonomatex_enterprise')
    op.drop_index(op.f('ix_autonomatex_enterprise_users_tenant_id'), table_name='users', schema='autonomatex_enterprise')
    op.drop_index(op.f('ix_autonomatex_enterprise_users_email'), table_name='users', schema='autonomatex_enterprise')
    op.drop_table('users', schema='autonomatex_enterprise')
    op.drop_index(op.f('ix_autonomatex_enterprise_tenants_slug'), table_name='tenants', schema='autonomatex_enterprise')
    op.drop_table('tenants', schema='autonomatex_enterprise')
    op.drop_index(op.f('ix_autonomatex_enterprise_roles_tenant_id'), table_name='roles', schema='autonomatex_enterprise')
    op.drop_table('roles', schema='autonomatex_enterprise')
    # ### end Alembic commands ###
